services:
  - type: web
    name: customer-project
    env: python
    pythonVersion: 3.13
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn mysite.wsgi:application --log-file -
