services:
  - type: web
    name: customer-revenue-app
    env: python
    buildCommand: |
      pip install --upgrade pip setuptools wheel
      pip install -r requirements.txt
    startCommand: gunicorn mysite.wsgi
